"""add_integrations_and_email_fields

Revision ID: 89a5593a5836
Revises: 005_add_stage4_gst_itc_fields
Create Date: 2026-08-27 16:08:00.595199

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

"""add_integrations_and_email_fields

Revision ID: 89a5593a5836
Revises: 005_add_stage4_gst_itc_fields
Create Date: 2026-08-27 16:08:00.595199

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '89a5593a5836'
down_revision: Union[str, None] = '005_add_stage4_gst_itc_fields'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('integrations', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('now()')))
    op.add_column('integrations', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('now()')))
    op.add_column('invoices', sa.Column('email_subject', sa.String(length=255), nullable=True))
    op.add_column('invoices', sa.Column('email_sender', sa.String(length=255), nullable=True))
    op.add_column('invoices', sa.Column('email_received_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('invoices', sa.Column('email_message_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'email_message_id')
    op.drop_column('invoices', 'email_received_at')
    op.drop_column('invoices', 'email_sender')
    op.drop_column('invoices', 'email_subject')
    op.drop_column('integrations', 'updated_at')
    op.drop_column('integrations', 'created_at')
    # ### end Alembic commands ###
